# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(210, 100, 391, 351))
        self.groupBox.setObjectName("groupBox")
        self.median_filter_2 = QtWidgets.QPushButton(self.groupBox)
        self.median_filter_2.setGeometry(QtCore.QRect(80, 60, 211, 28))
        self.median_filter_2.setObjectName("median_filter_2")
        self.gaussian_filter = QtWidgets.QPushButton(self.groupBox)
        self.gaussian_filter.setGeometry(QtCore.QRect(80, 160, 211, 28))
        self.gaussian_filter.setObjectName("gaussian_filter")
        self.bilateral_filter = QtWidgets.QPushButton(self.groupBox)
        self.bilateral_filter.setGeometry(QtCore.QRect(82, 250, 211, 28))
        self.bilateral_filter.setObjectName("bilateral_filter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "2. Image smoothing"))
        self.median_filter_2.setText(_translate("MainWindow", "2.1 median filter"))
        self.gaussian_filter.setText(_translate("MainWindow", "2.2 Gaussian filter"))
        self.bilateral_filter.setText(_translate("MainWindow", "2.3 bilateral_filter"))
